// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8_dSXVIDILdPXEzxJ7zc2PXGAxEuV0jM',
    appId: '1:819702262701:web:413251f3e2398a983b0f24',
    messagingSenderId: '819702262701',
    projectId: 'arpin-48903',
    authDomain: 'arpin-48903.firebaseapp.com',
    databaseURL: 'https://arpin-48903-default-rtdb.firebaseio.com',
    storageBucket: 'arpin-48903.appspot.com',
    measurementId: 'G-DR4MWVG5V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH2ziyaEIYnO-ECOfCelLIYUDCcp-n1NM',
    appId: '1:819702262701:android:3018f81cf12700a63b0f24',
    messagingSenderId: '819702262701',
    projectId: 'arpin-48903',
    databaseURL: 'https://arpin-48903-default-rtdb.firebaseio.com',
    storageBucket: 'arpin-48903.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBApPBqnn5I6GwgPSPoPNnCxW_rwXjICqE',
    appId: '1:819702262701:ios:fcb593e192bd05f83b0f24',
    messagingSenderId: '819702262701',
    projectId: 'arpin-48903',
    databaseURL: 'https://arpin-48903-default-rtdb.firebaseio.com',
    storageBucket: 'arpin-48903.appspot.com',
    iosBundleId: 'com.example.arPin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBApPBqnn5I6GwgPSPoPNnCxW_rwXjICqE',
    appId: '1:819702262701:ios:781b052f842d1ac43b0f24',
    messagingSenderId: '819702262701',
    projectId: 'arpin-48903',
    databaseURL: 'https://arpin-48903-default-rtdb.firebaseio.com',
    storageBucket: 'arpin-48903.appspot.com',
    iosBundleId: 'com.example.arPin.RunnerTests',
  );
}
